Info/__init__.py
import logging
from logging.handlers import RotatingFileHandler

import redis
from flask import Flask, session, render_template, g
from flask_session import Session
from flask_sqlalchemy import SQLAlchemy

from config import ConfigDict

db = SQLAlchemy()
Redis_store = None


def create_app(env):
    app = Flask(__name__)
    # 给APP添加配置信息
    current_app_config = ConfigDict[env]
    app.config.from_object(current_app_config)
    # 配置日志信息
    # 调用记录日志函数
    log_file(current_app_config.LOG_LV)

    db.init_app(app)
    global Redis_store
    Redis_store = redis.StrictRedis(host=current_app_config.REDIS_HOST, port=current_app_config.REDIS_PORT)
    Session(app)

    # 添加csrf防护,验证前端与后端是否一致
    from flask_wtf import CSRFProtect
    CSRFProtect(app)

    from flask_wtf.csrf import generate_csrf
    @app.after_request
    def after_request(response):
        # 生成token
        csrf_token = generate_csrf()
        # 传给前端csrf值
        response.set_cookie('csrf_token', csrf_token)
        return response

    # 生成一个过滤器给前端去展示首页的点击排行页面
    from Info.utils.common import to_class_index
    app.add_template_filter(to_class_index, "to_class_name")
    # 注册蓝图
    from Info.modules.index import index_blu
    app.register_blueprint(index_blu)
    from Info.modules.passport import passport_blu
    app.register_blueprint(passport_blu)
    from Info.modules.news_detail import news_detail_blu
    app.register_blueprint(news_detail_blu)
    from Info.modules.profile import profile_blu
    app.register_blueprint(profile_blu)
    from Info.modules.admin import admin_blu
    app.register_blueprint(admin_blu)

    from Info.utils.common import get_login_data
    @app.errorhandler(404)
    @get_login_data
    def page_not_found(_):
        user = g.user
        data = {
            "user_info": user.to_dict() if user else None,
        }
        return render_template('news/404.html',data=data )

    return app


def log_file(lv):
    """记录日志信息"""
    # 设置哪些日志信息等级要被记录
    logging.basicConfig(level=lv)  # 调试debug级
    # 创建日志记录器，指明日志保存的路径、每个日志文件的最大大小、保存的日志文件个数上限
    file_log_handler = RotatingFileHandler("logs/log", maxBytes=1024 * 1024 * 100, backupCount=10)
    # 创建日志记录的格式 日志等级 输入日志信息的文件名 行数 日志信息
    formatter = logging.Formatter('%(levelname)s %(filename)s:%(lineno)d %(message)s')
    # 为刚创建的日志记录器设置日志记录格式
    file_log_handler.setFormatter(formatter)
    # 为全局的日志工具对象（flask app使用的）添加日志记录器
    logging.getLogger().addHandler(file_log_handler)

Info/modules/__init__.py
"""
    专门存放各种模块,比如首页模块，用户模块，后台管理模块```````
"""

Info/modules/admin/__init__.py
from flask import Blueprint, session, redirect, request

admin_blu = Blueprint('admin', __name__, url_prefix='/admin')

from . import views


@admin_blu.before_request
def check_admin():
    is_admin = session.get('is_admin')
    if not is_admin and not request.url.endswith('/admin/login'):
        return redirect('/')

Info/modules/admin/views.py
from Info import db
from Info.constants import ADMIN_USER_PAGE_MAX_COUNT, QINIU_DOMIN_PREFIX
from Info.models import User, News, Category
from Info.utils.qiniu_pro import qinniu_storage
from Info.utils.response_code import RET
from . import admin_blu
from flask import render_template, request, current_app, session, redirect, url_for, jsonify


@admin_blu.route('/login', methods=['GET', 'POST'])
def admin_login():
    """
    如果是get请求，直接返回登录页面
    如果是post请求：
        1.拿到参数并进行判空
        2.查询数据库看用户是否存在
        3.校验密码是否通过
        4.校验是否是管理员
        5.保存用户登录信息
        6.返回登录成功页面
    :return:
    """
    if request.method == 'GET':
        user_id = session.get('user_id', None)
        is_admin = session.get('is_admin', False)
        if user_id and is_admin:
            return redirect(url_for("admin.admin_index"))
        return render_template('admin/login.html')
    username = request.form.get('username')
    password = request.form.get('password')
    if not all([username, password]):
        return render_template('admin/login.html', errmsg='参数不足')
    try:
        user = User.query.filter(User.mobile == username).first()
    except Exception as e:
        current_app.logger.error(e)
        return render_template('admin/login.html', errmsg='数据查询失败')
    if not user:
        return render_template('admin/login.html', errmsg='用户不存在')
    if not user.check_passowrd(password):
        return render_template('admin/login.html', errmsg='账号或者密码不正确')
    if not user.is_admin:
        return render_template('admin/login.html', errmsg='无登录权限')
    session['nick_name'] = username
    session['mobile'] = user.mobile
    session['user_id'] = user.id
    session['is_admin'] = True
    return redirect(url_for('admin.admin_index'))


@admin_blu.route('/index', methods=['GET', 'POST'])
def admin_index():
    """
    直接手打/admin/index，需要进行判断是否是管理员，如果是则返回admin/index页面，如果不是则跳转到主页面
    通过钩子函数@admin_blu.before_reuqest：def check_admin实现
    :return:
    """
    return render_template('admin/index.html')


@admin_blu.route('/logout')
def logout():
    session.pop('user_id')
    session.pop('nick_name')
    session.pop('mobile')
    session.pop('is_admin')
    return redirect('/admin/login')


@admin_blu.route('/user_count')
def user_count():
    """
    :return:用户总数，用户月新增数，用户日新增数
    用户总数可以通过查询来得到
    月新增数需要通过函数来得到
    日新增数需要通过函数来得到
    """
    total_count = 0
    try:
        total_count = User.query.filter(User.is_admin == False).count()
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DATAERR, errmsg='查询数据库失败')

    # 月新增数
    month_count = 0
    import time
    from datetime import datetime, timedelta
    t = time.localtime()
    cur_mon_str = '%d-%02d-01' % (t.tm_year, t.tm_mon)
    cur_mon = datetime.strptime(cur_mon_str, "%Y-%m-%d")
    try:
        month_count = User.query.filter(User.is_admin == False, User.create_time >= cur_mon).count()
    except Exception as e:
        current_app.logger.error(e)
    # 日新增数
    day_count = 0
    cur_day_str = '%d-%02d-%02d' % (t.tm_year, t.tm_mon, t.tm_mday)
    cur_day = datetime.strptime(cur_day_str, "%Y-%m-%d")
    try:
        month_count = User.query.filter(User.is_admin == False, User.create_time >= cur_mon).count()
    except Exception as e:
        current_app.logger.error(e)
    # 折线图
    active_time = []
    active_count = []
    for i in range(0, 31):
        startday = cur_day - timedelta(days=i)
        endday = cur_day - timedelta(days=(i - 1))
        cot = User.query.filter(User.is_admin == False, User.last_login >= startday, User.last_login < endday).count()
        active_count.append(cot)
        active_time.append(startday.strftime("%Y-%m-%d"))
    active_time.reverse()
    active_count.reverse()
    data = {
        "total_count": total_count,
        "month_count": month_count,
        "day_count": day_count,
        "active_time": active_time,
        "active_count": active_count
    }
    return render_template('admin/user_count.html', data=data)


@admin_blu.route('/user_list')
def user_list():
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p = 1
    users = []
    total_page = 1
    cur_page = 1
    try:
        paginate = User.query.filter(User.is_admin == False).order_by(User.last_login.desc()).paginate(p,
                                                                                                       ADMIN_USER_PAGE_MAX_COUNT)
        items = paginate.items
        total_page = paginate.pages
        cur_page = paginate.page
    except Exception as e:
        current_app.logger.error(e)
    user_list = []
    if items:
        for i in items:
            user_list.append(i.to_dict())
    data = {
        "user_list": user_list,
        "total_page": total_page,
        "cur_page": cur_page

    }
    return render_template('admin/user_list.html', data=data)


@admin_blu.route('/news_review')
def news_review():
    """
    参数：当前页面p，通过get请求获取
    :return: id	标题	发布时间	状态	管理操作
    """
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p = 1
    news = []
    total_page = 1
    cur_page = 1
    try:
        paginate = News.query.filter(News.status == 1).order_by(News.create_time.desc()).paginate(p,
                                                                                                  ADMIN_USER_PAGE_MAX_COUNT)
        items = paginate.items
        total_page = paginate.pages
        cur_page = paginate.page
    except Exception as e:
        current_app.logger.error(e)
    newslist = []
    for i in items:
        newslist.append(i.to_review_dict())
    data = {
        "newslist": newslist,
        "total_page": total_page,
        "cur_page": cur_page
    }
    return render_template('admin/news_review.html', data=data)


@admin_blu.route('/news_review_detail/<int:news_id>')
def news_review_detail(news_id):
    """
    参数：需要审核的新闻的id
    :return:
    """
    if request.method == 'GET':
        news = None
        try:
            news = News.query.get(news_id)
        except Exception as e:
            current_app.logger.error(e)
        if not news:
            return jsonify(errno=RET.NODATA, errmsg='新闻不存在')
    data = {
        "news": news.to_dict()
    }
    return render_template('admin/news_review_detail.html', data=data)


@admin_blu.route('/news_review_action', methods=['POST'])
def news_review_action():
    """
    :param  "action": action,
            "news_id": news_id,
            "reason": reason
    :return:
    """
    param_dict = request.json
    news_id = param_dict.get('news_id')
    action = param_dict.get('action')
    if not all([news_id, action]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不完整')

    if action not in ('accept', 'reject'):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不正确')

    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DATAERR, errmsg='数据库查询失败')
    if not news:
        return jsonify(errno=RET.NODATA, errmsg="未查询到数据")
    if action == 'accept':
        news.status = 0
    else:
        reason = param_dict.get('reason')
        if not reason:
            return jsonify(errno=RET.PARAMERR, errmsg="请输入拒绝原因")
        news.status = -1
        news.reason = reason
    try:
        db.session.commit()
    except Exception as e:
        current_app.logger.error(e)
        db.session.rollback()
        return jsonify(errno=RET.DBERR, errmsg="数据库操作失败")
    return jsonify(errno=RET.OK, errmsg='操作成功')


@admin_blu.route('/news_edit')
def news_edit():
    """
    :param
    :return:
    """
    p = request.args.get("p", 1)
    try:
        p = int(p)
    except Exception as e:
        current_app.logger.error(e)
        p = 1
    news = []
    total_page = 1
    cur_page = 1
    try:
        paginate = News.query.filter(News.status == 0).order_by(News.create_time.desc()).paginate(p,
                                                                                                  ADMIN_USER_PAGE_MAX_COUNT)
        items = paginate.items
        total_page = paginate.pages
        cur_page = paginate.page
    except Exception as e:
        current_app.logger.error(e)
    newslist = []
    for i in items:
        newslist.append(i.to_review_dict())
    data = {
        "newslist": newslist,
        "total_page": total_page,
        "cur_page": cur_page
    }
    return render_template("admin/news_edit.html", data=data)


@admin_blu.route('/news_edit_detail/<int:news_id>')
def news_edit_detail(news_id):
    news = None
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
        return jsonify(errno=RET.DBERR, errmsg="新闻不存在")
    try:
        categories = Category.query.all()
    except Exception as e:
        current_app.logger.error(e)
    category_lst = []
    for i in categories:
        category_lst.append(i.to_dict())
    data = {
        "news": news.to_dict(),
        "category_lst": category_lst
    }
    return render_template("admin/news_edit_detail.html", data=data)


@admin_blu.route('/news_edit_action', methods=['POST'])
def news_edit_action():
    """
    param news_id
    :return:
    """
    news_id = request.form.get('news_id')
    title = request.form.get('title')
    digest = request.form.get('digest')
    content = request.form.get('content')
    index_image = request.form.get('index_image')
    category_id = request.form.get('category_id')
    if not all([title, digest, content, category_id]):
        return jsonify(errno=RET.PARAMERR, errmsg='参数不完整')
    try:
        news = News.query.get(news_id)
    except Exception as e:
        current_app.logger.error(e)
    if not news:
        return jsonify(errno=RET.NODATA, errmsg='新闻查询不到')
    if index_image:
        try:

Info/modules/index/__init__.py
"""
    创建index蓝图
"""
from flask import Blueprint
index_blu = Blueprint('index', __name__)
from . import views

Info/modules/index/views.py
from Info import Redis_store
from Info.constants import HOME_PAGE_MAX_NEWS
from Info.models import User, News, Category
from Info.modules.index import index_blu
from flask import render_template, current_app, session, request, jsonify

from Info.utils.response_code import RET


@index_blu.route('/')
def index():
    # 1.获取到登录信息
    user_id = session.get('user_id')
    # 2.通过id获取用户信息
    user = None
    if user_id:
        try:
            user = User.query.get(user_id)
        except Exception as e:
            current_app.logger.error(e)
    try:
        news_obj = News.query.order_by(News.clicks.desc()).limit(6)
    except Exception as e:
        current_app.logger.error(e)

    # 查询首页导航部分并进行展示
    try:
        news_category = Category.query.all()
    except Exception as e:
        current_app.logger.error(e)
    # 返回所有的数据
    data = {
        "user_info": user.to_dict() if user else None,
        "news_obj": news_obj,
        "news_category": news_category
    }
    return render_template('news/index.html', data=data)


@index_blu.route('/favicon.ico')
def get_favicon():
    # return current_app.send_static_file('news/favicon.ico')
    return current_app.send_static_file("news/favicon.ico")


@index_blu.route('/news_list')
def news_list():
    param_dict = request.args
    page = param_dict.get('page', 1)
    cid = param_dict.get('cid', 1)
    per_page = param_dict.get('per_page', HOME_PAGE_MAX_NEWS)
    try:
        page = int(page)
        cid = int(cid)
        per_page = int(per_page)
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DATAERR, errmsg='参数错误')

    filters = [News.status == 0]
    if cid != 1:
        filters.append(News.category_id == cid)
    try:
        NewsPaginationObj = News.query.filter(*filters).order_by(News.create_time.desc()).paginate(page, per_page,
                                                                                                   False)
        items = NewsPaginationObj.items  # 查询到的第page页的数据(其实是python的模型对象列表)
        total_page = NewsPaginationObj.pages
        current_page = NewsPaginationObj.page
    except Exception as e:
        current_app.logger.error(e)
        return jsonify(errno=RET.DBERR, errmsg="数据查询失败")
    # 返回数据之前需要把每一个模型对象转换成字典格式，因为js不认识python的模型对象
    news_dict = []
    for i in items:
        news_dict.append(i.to_basic_dict())
    return jsonify(errno=RET.OK, errmsg='OK', newsList=news_dict, totalPage=total_page, currentPage=current_page)

Info/modules/news_detail/__init__.py
from flask import Blueprint

news_detail_blu = Blueprint('news_detail', __name__, url_prefix='/news_detail')
from . import views

Info/modules/passport/__init__.py
"""
    主要负责写关于注册时候图片验证以及短信验证的代码
"""
from flask import Blueprint
passport_blu = Blueprint('passport', __name__, url_prefix='/passport')
from . import views

Info/modules/profile/__init__.py
from flask import Blueprint

profile_blu = Blueprint('profile', __name__, url_prefix='/user')

from . import views

Info/templates/news/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block Title %}首页-新经资讯{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="../../static/news/css/reset.css">
    <link rel="stylesheet" type="text/css" href="../../static/news/css/main.css">
    <script type="text/javascript" src="../../static/news/js/jquery-1.12.4.min.js"></script>
    {% block ScriptBlock %}
        <script type="text/javascript" src="../../static/news/js/index.js"></script>
    {% endblock %}
    <script type="text/javascript" src="../../static/news/js/main.js"></script>
</head>
<body>
    <div class="header_con">
    <div class="header_con">
        <div class="header">
            <a href="/" class="logo fl"><img src="../../static/news/images/logo.png" alt="logo"></a>
            {% block LeftTopBlock %}
                <ul class="menu fl">
                {% for category in data.news_category %}
                <li class="{% if loop.index==1 %}category{% endif %}" data-cid="{{ loop.index }}"><a href="javascript:;">{{ category.name }}</a></li>
                {% endfor %}
{#                <li data-cid="2"><a href="javascript:;">股市</a></li>#}
{#                <li data-cid="3"><a href="javascript:;">债市</a></li>#}
{#                <li data-cid="4"><a href="javascript:;">商品</a></li>#}
{#                <li data-cid="5"><a href="javascript:;">外汇</a></li>#}
{#                <li data-cid="6"><a href="javascript:;">公司</a></li>#}
            </ul>
            {% endblock %}

            {% if not data.user_info %}
                <div class="user_btns fr">
                    <a href="javascript:;" class="login_btn">登录</a> / <a href="javascript:;" class="register_btn">注册</a>
                </div>
            <!-- 用户登录后显示下面，隐藏上面 -->
            {% else %}
            <div class="user_login fr">
                <img src="{% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png {% endif %}" class="lgin_pic">
                <a href="{{ url_for('profile.info') }}" id="nick_name">{{ data.user_info.nick_name }}</a>
                <a href="#" onclick="logout()">退出</a>
            </div>
            {% endif %}
        </div>
    </div>
    {% block Conter_con %}
        <div class="conter_con">
        {% block LeftBlock %}
            <ul class="list_con fl">
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="author fl">
                        <img src="../../static/news/images/person.png" alt="author">
                        <a href="#">乐鸣</a>
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
            <li>
                <a href="#" class="news_pic fl"><img src="../../static/news/images/news_pic.jpg"></a>
                <a href="#" class="news_title fl">日本史上最大IPO之一要来了：软银计划将手机业务分拆上市</a>
                <a href="#" class="news_detail fl">据日经新闻网，软银计划让旗下核心业务移动手机部门SoftBank Corp.分拆上市，或募资2万亿日元(约180亿美元)。随着软银逐步向投资公司转型，此举旨在给手机业务部门更多自主权。</a>
                <div class="author_info fl">
                    <div class="source fl">
                        来源：广州日报
                    </div>
                    <div class="time fl">2017-01-01 00:00:00</div>
                </div>
            </li>
        </ul>
        {% endblock %}
        {% block ContentBlock %}
            <div class="rank_con fr">

            {% block RightBlock %}

            {% endblock %}
            <div class="rank_title">
                <h3>点击排行</h3>
            </div>
            <ul class="rank_list">
                {% for news in data.news_obj %}
                    <li><span class={{ loop.index | to_class_name }}>{{ loop.index }}</span><a href="/news_detail/{{ news.id }}">{{ news.title }}</a></li>
                {% endfor %}
{#                <li><span class="second">2</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span class="third">3</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
{#                <li><span>4</span><a href="#">势如破竹！人民币再度连闯四道关口 在岸、离岸双双升破6.42</a></li>#}
{#                <li><span>5</span><a href="#">凛冬已至，还有多少银行人在假装干银行</a></li>#}
{#                <li><span>6</span><a href="#">人民日报：部分城市楼市放松限制引关注，楼市调控不会“拉抽屉”</a></li>#}
            </ul>
        </div>
        {% endblock %}
    </div>
    {% endblock %}

    {% block Footerblock %}
        <div class="footer">
        <div class="footer_links">
            <a href="">关于我们</a>
            <span>|</span>
            <a href="">联系我们</a>
            <span>|</span>
            <a href="">招聘人才</a>
            <span>|</span>
            <a href="">友情链接</a>
        </div>
        <p class="copyright">
            CopyRight © 2018 新经资讯信息技术有限公司 All Rights Reserved<br />
电话：010-****888    京ICP备*******8号
        </p>
    </div>
    {% endblock %}

    
    <!-- 登录表单 -->
    <form class="login_form_con">
        <div class="login_form">
            <div class="login_title">
                <h3>登 录</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input id="mobile" type="text" name="mobile" autocomplete="off">
                <div class="input_tip">手机号</div>
                <div id="login-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input id="password" type="password" name="password">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="login-password-err" class="error_tip">密码不能为空</div>
            </div>
            <input type="submit" name="" value="登 录" class="input_sub">
            <div class="down_link">还没有账号？<a href="javascript:;" class="to_register">立即注册</a></div>
        </div>
        <div class="mask"></div>
    </form>

    <!-- 注册表单 -->
    <form class="register_form_con">
        <div class="register_form">
            <div class="register_title">
                <h3>注 册</h3>
                <a href="javascript:;" class="shutoff"></a>
            </div>
            <div class="form_group">
                <input type="text" name="mobile" autocomplete="off" id="register_mobile" class="phone_input">
                <div class="input_tip">手机号</div>
                <div id="register-mobile-err" class="error_tip">手机号不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="code_pwd" id="imagecode" class="code_pwd">
                <div class="input_tip">图形验证码</div>
                <img src="../../static/news/images/pic_code.png" class="get_pic_code" onclick="generateImageCode()">
                <div id="register-image-code-err" class="error_tip">图形码不能为空</div>
            </div>
            <div class="form_group">
                <input type="text" name="smscode" id="smscode" class="code_pwd">
                <div class="input_tip">手机验证码</div>
                <a href="javascript:;" class="get_code" onclick="sendSMSCode()">点击获取验证码</a>
                <div id="register-sms-code-err" class="error_tip">验证码不能为空</div>
            </div>
            <div class="form_group">
                <input type="password" name="password" id="register_password" class="pass_input">
                <div class="input_tip">密码(不少于6位)</div>
                <div id="register-password-err" class="error_tip">密码不能为空</div>
            </div>
            <div  class="form_group2 clearfix">
                <input type="checkbox" class="agree_input" checked>
                <p>同意使用条款，并已阅读"跟帖评论自律管理承诺书"</p>
                <div class="error_tip">请勾选</div>
            </div>
            <input type="submit" name="" value="注 册" class="input_sub">
            <div class="down_link">已有账号？<a href="javascript:;" class="to_login">立即登录</a></div>
        </div>
        <div class="mask"></div>
    </form>
</body>
</html>

Info/templates/news/user.html
{% extends 'news/base.html' %}
{% block Title %}用户中心{% endblock %}
{% block ScriptBlock %}<script type="text/javascript" src="../../static/news/js/jquery.form.min.js"></script>{% endblock %}
{% block LeftTopBlock %}{% endblock %}
{% block Conter_con %}
<div class="conter_con">
		<div class="user_menu_con fl">
			<div class="user_center_pic">
				<img src="{% if data.user_info.avatar_url %}{{ data.user_info.avatar_url }}{% else %}../../static/news/images/person01.png {% endif %}" alt="用户图片">
			</div>
			<div class="user_center_name">{{ data.user_info.nick_name }}</div>

			<ul class="option_list">
				<li class="active"><a href="{{ url_for('profile.base_info') }}" target="main_frame">基本资料</a></li>
				<li><a href="{{ url_for('profile.pic_info') }}" target="main_frame">头像设置</a></li>
				<li><a href="../../static/news/html/user_follow.html" target="main_frame">我的关注</a></li>
				<li><a href="{{ url_for('profile.pass_info') }}" target="main_frame">密码修改</a></li>
				<li><a href="{{ url_for('profile.collect_news') }}" target="main_frame">我的收藏</a></li>
				<li><a href="{{ url_for('profile.news_release') }}" target="main_frame">新闻发布</a></li>
				<li><a href="{{ url_for('profile.news_list') }}" target="main_frame">新闻列表</a></li>
			</ul>
		</div>

		<div class="user_con fr">
			<iframe src="{{ url_for('profile.base_info') }}" frameborder="0" name="main_frame" class="main_frame" id="main_frame"></iframe>
		</div>
	</div>
{% endblock %}